function [poster,wall] = poster_LifeAquatic()
  poster = definePosterProperties(26, ...
                                  37 + (3/4), ...
                                  5.5, ...
                                  'centered', ...
                                  1.5, ...
                                  [124, 189, 156]./255, ...
                                  [208, 172, 89]./255);
  wall =   defineWallProperties(71 + 1/4, ...
                                73, ...
                                [229, 228, 215]./255, ...
                                'thirds', ...
                                'inches');
end